#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_repo="${LEGION_SOURCE_DIR:-$HOME/legion-server-sources/LegionCore-7.3.5V2}"
expected_commit="6c41d0faa23474bf9e76a4811b144d43e9545bab"
verify_dir="$(mktemp -d /tmp/legion-patch-verify.XXXXXX)"

cleanup() {
    case "$verify_dir" in
        /tmp/legion-patch-verify.*) rm -rf -- "$verify_dir" ;;
        *) echo "Refusing to remove unexpected verification path: $verify_dir" >&2 ;;
    esac
}
trap cleanup EXIT

git clone -q --shared "$source_repo" "$verify_dir/source"
git -C "$verify_dir/source" reset -q --hard "$expected_commit"

for patch_file in "$repo_root"/patches/*.patch; do
    git -C "$verify_dir/source" apply "$patch_file"
done

install -m 0644 "$repo_root/overlays/companion_autoloot.cpp" \
    "$verify_dir/source/src/server/scripts/Custom/companion_autoloot.cpp"
install -m 0644 "$repo_root/overlays/startup_qol.cpp" \
    "$verify_dir/source/src/server/scripts/Custom/startup_qol.cpp"
install -m 0644 "$repo_root/overlays/rocket_rescue.cpp" \
    "$verify_dir/source/src/server/scripts/Custom/rocket_rescue.cpp"

git -C "$verify_dir/source" diff --check
grep -q 'AddSC_companion_autoloot' "$verify_dir/source/src/server/scripts/ScriptLoader.cpp"
grep -q 'AddSC_startup_qol' "$verify_dir/source/src/server/scripts/ScriptLoader.cpp"
grep -q 'AddSC_rocket_rescue' "$verify_dir/source/src/server/scripts/ScriptLoader.cpp"
grep -q 'spell_rocket_rescue_guided_payload' "$verify_dir/source/src/server/scripts/Custom/rocket_rescue.cpp"
grep -q 'GetSpell()->m_targets.SetSpeed(0.0f)' "$verify_dir/source/src/server/scripts/Custom/rocket_rescue.cpp"
grep -q 'overlays/rocket_rescue.cpp' "$repo_root/scripts/verify-managed-source.sh"
grep -q 'StartupQoL.Enable = 0' "$verify_dir/source/src/server/worldserver/worldserver.conf.dist"
grep -q 'StartupQoL.ZoneFlying = 1' "$verify_dir/source/src/server/worldserver/worldserver.conf.dist"
grep -q 'StartupQoL.ZoneFlying = 1' "$repo_root/patches/0032-add-zone-flying-qol-config.patch"
grep -q 'ZoneFlyingSpells' "$verify_dir/source/src/server/scripts/Custom/startup_qol.cpp"
grep -q '90267.*Flight Master' "$verify_dir/source/src/server/scripts/Custom/startup_qol.cpp"
grep -q '115913.*Wisdom of the Four Winds' "$verify_dir/source/src/server/scripts/Custom/startup_qol.cpp"
grep -q '191645.*Draenor Pathfinder' "$verify_dir/source/src/server/scripts/Custom/startup_qol.cpp"
grep -q '233368.*Broken Isles Pathfinder' "$verify_dir/source/src/server/scripts/Custom/startup_qol.cpp"
grep -q 'silentRemote' "$verify_dir/source/src/server/game/Entities/Player/Player.cpp"
grep -q 'lootPesonal->isOpen = true' "$verify_dir/source/src/server/game/Entities/Player/Player.cpp"
grep -q 'DoLootRelease(ObjectGuid lguid, bool ignoreDistance' "$verify_dir/source/src/server/game/Handlers/LootHandler.cpp"
grep -q 'CompanionAutoLoot.Radius = 40' "$verify_dir/source/src/server/worldserver/worldserver.conf.dist"
grep -q '!questItem && item->is_blocked' "$verify_dir/source/src/server/scripts/Custom/companion_autoloot.cpp"
grep -q 'loot->AllowedForPlayer(player' "$verify_dir/source/src/server/scripts/Custom/companion_autoloot.cpp"
grep -q 'PlayedTimeReward] You received' "$verify_dir/source/src/server/game/Entities/Player/Player.cpp"
grep -q 'Redeemed 10 Nordrassil Coins' "$verify_dir/source/src/server/scripts/World/custom_events.cpp"
grep -q 'Your Shop balance is:' "$verify_dir/source/src/server/game/BattlePay/BattlePayMgr.cpp"
grep -q 'restart chase movement and combat after death cleanup' "$verify_dir/source/src/server/game/Entities/Creature/Creature.cpp"
grep -q 'WorldPackets::Quest::QuestPoiChanged().Write()' "$verify_dir/source/src/server/game/Entities/Player/Player.cpp"
grep -q 'bool sentFollowupMenu = false' "$verify_dir/source/src/server/game/Handlers/QuestHandler.cpp"
grep -q 'menuItem.QuestId != packet.QuestID' "$verify_dir/source/src/server/game/Handlers/QuestHandler.cpp"
grep -q 'case 196884: // Feral Lunge' "$verify_dir/source/src/server/game/Spells/SpellEffects.cpp"
grep -q 'Use the configured quest' "$verify_dir/source/src/server/game/Globals/QuestData.cpp"
grep -q 'ObjectiveIndex == -1' "$verify_dir/source/src/server/game/Globals/QuestData.cpp"
grep -q 'POI.points.assign(1, \*nearestEnder)' "$verify_dir/source/src/server/game/Globals/QuestData.cpp"
grep -q 'using QuestPOIPointKey = std::tuple' "$verify_dir/source/src/server/game/Globals/QuestData.cpp"
grep -q 'VerifiedBuild FROM quest_poi_points' "$verify_dir/source/src/server/game/Globals/QuestData.cpp"
grep -q 'skippedMismatchedPointBuilds' "$verify_dir/source/src/server/game/Globals/QuestData.cpp"
grep -q 'intentionally refactored by the verified-build POI patch' "$repo_root/scripts/build-core.sh"
grep -q 'intentionally narrowed by the melee-class guard patch' "$repo_root/scripts/build-core.sh"
grep -q 'CONFIG_CREATURE_CASTER_AI_FALLBACK' "$verify_dir/source/src/server/game/AI/CreatureAISelector.cpp"
grep -q 'creature_template_spell' "$verify_dir/source/src/server/game/AI/CoreAI/CombatAI.cpp"
grep -q 'GetCasterAISpellCooldown' "$verify_dir/source/src/server/game/AI/CoreAI/CombatAI.cpp"
grep -q 'spell->cooldown + urand(0, spell->cooldown)' "$verify_dir/source/src/server/game/AI/CoreAI/CombatAI.cpp"
grep -q 'AITARGET_BUFF || !me->HasAura(spellId)' "$verify_dir/source/src/server/game/AI/CoreAI/CombatAI.cpp"
grep -q 'creature->getClass() != UNIT_CLASS_MAGE' "$verify_dir/source/src/server/game/AI/CreatureAISelector.cpp"
grep -q 'bool missingSmartAI' "$verify_dir/source/src/server/game/AI/CreatureAISelector.cpp"
grep -q 'legacy spell1-spell8 columns and creature_template_spell' "$verify_dir/source/src/server/game/AI/CoreAI/CombatAI.cpp"
grep -q 'std::find(spells.begin(), spells.end(), spellId)' "$verify_dir/source/src/server/game/AI/CoreAI/CombatAI.cpp"
grep -q 'std::max<uint32>(AISpellInfo\[spellId\].cooldown, 5000)' "$verify_dir/source/src/server/game/AI/CoreAI/CombatAI.cpp"
grep -q 'CreatureAI.CasterFallback.Enable = 1' "$verify_dir/source/src/server/worldserver/worldserver.conf.dist"
grep -q 'RegisterBattlePayProductScript(name, this)' "$verify_dir/source/src/server/game/Scripting/ScriptMgr.cpp"
grep -q 'AddSC_BattlePayScripts();' "$verify_dir/source/src/server/scripts/ScriptLoader.cpp"
grep -q '^void AddSC_BattlePayScripts()' "$verify_dir/source/src/server/scripts/ScriptLoader.cpp"
if grep -q '^void AddBattlePayScripts()' "$verify_dir/source/src/server/scripts/ScriptLoader.cpp"; then
    echo "Orphaned BattlePay loader name is still present" >&2
    exit 1
fi
grep -q 'SKILL_FIRST_AID,      3273' "$verify_dir/source/src/server/scripts/BattlePay/battlepay_professions.cpp"
grep -q 'SKILL_FISHING,        7620' "$verify_dir/source/src/server/scripts/BattlePay/battlepay_professions.cpp"
grep -q 'SKILL_BLACKSMITHING, 5956' "$verify_dir/source/src/server/scripts/BattlePay/battlepay_professions.cpp"
grep -q 'SKILL_MINING,        2901' "$verify_dir/source/src/server/scripts/BattlePay/battlepay_professions.cpp"
grep -q 'SKILL_SKINNING,      7005' "$verify_dir/source/src/server/scripts/BattlePay/battlepay_professions.cpp"
grep -q 'SKILL_FISHING,       6256' "$verify_dir/source/src/server/scripts/BattlePay/battlepay_professions.cpp"
grep -q 'HasItemCount(toolItr->second, 1, true)' "$verify_dir/source/src/server/scripts/BattlePay/battlepay_professions.cpp"
if grep -q 'player->getLevel() < 90' "$verify_dir/source/src/server/scripts/BattlePay/battlepay_professions.cpp"; then
    echo "Profession products still require level 90" >&2
    exit 1
fi
grep -q 'Adds 10 coins to your in-game Shop balance' "$repo_root/database/70-nordrassil-coin-localization.sql"
grep -q '7005056, 2442913102, 505056' "$repo_root/database/70-nordrassil-coin-localization.sql"
grep -q 'azerothlab_removed_creature_spawns' "$repo_root/database/80-deduplicate-static-creature-spawns.sql"
grep -q '125434' "$repo_root/database/80-deduplicate-static-creature-spawns.sql"
grep -q '_alw_nearby_singleton_candidates' "$repo_root/database/81-deduplicate-nearby-singleton-npcs.sql"
grep -q 'database/81-deduplicate-nearby-singleton-npcs.sql' "$repo_root/scripts/apply-required-updates.sh"
grep -q '_alw_cross_generation_candidates' "$repo_root/database/82-deduplicate-nearby-cross-generation-creatures.sql"
grep -q 'newer`.`id` = `older`.`id' "$repo_root/database/82-deduplicate-nearby-cross-generation-creatures.sql"
grep -q 'database/82-deduplicate-nearby-cross-generation-creatures.sql' "$repo_root/scripts/apply-required-updates.sh"
grep -q 'azerothlab_removed_creature_template_addons' "$repo_root/database/83-remove-broken-syndicate-thief-sleep.sql"
grep -q '24477' "$repo_root/database/83-remove-broken-syndicate-thief-sleep.sql"
grep -q '42648' "$repo_root/database/83-remove-broken-syndicate-thief-sleep.sql"
grep -q 'database/83-remove-broken-syndicate-thief-sleep.sql' "$repo_root/scripts/apply-required-updates.sh"
grep -q '_alw_dormant_waypoint_candidates' "$repo_root/database/84-restore-dormant-creature-waypoints.sql"
grep -q 'first_node.*position_x' "$repo_root/database/84-restore-dormant-creature-waypoints.sql"
grep -q 'database/84-restore-dormant-creature-waypoints.sql' "$repo_root/scripts/apply-required-updates.sh"
grep -q '_alw_ambient_wander_candidates' "$repo_root/database/85-add-safe-outdoor-ambient-wander.sql"
grep -q 'spawndist.*= 3' "$repo_root/database/85-add-safe-outdoor-ambient-wander.sql"
grep -q 'azerothlab_ambient_wander_creature_backup' "$repo_root/database/85-add-safe-outdoor-ambient-wander.sql"
grep -q 'database/85-add-safe-outdoor-ambient-wander.sql' "$repo_root/scripts/apply-required-updates.sh"
grep -q '_alw_vilebranch_missing_smartai' "$repo_root/database/86-restore-vilebranch-combat-ai.sql"
grep -q '11015' "$repo_root/database/86-restore-vilebranch-combat-ai.sql"
grep -q '11016' "$repo_root/database/86-restore-vilebranch-combat-ai.sql"
grep -q '74613' "$repo_root/database/86-restore-vilebranch-combat-ai.sql"
grep -q 'NOT EXISTS' "$repo_root/database/86-restore-vilebranch-combat-ai.sql"
grep -q 'database/86-restore-vilebranch-combat-ai.sql' "$repo_root/scripts/apply-required-updates.sh"
grep -q 'database/86-restore-vilebranch-combat-ai.sql' "$repo_root/scripts/prepare-runtime.sh"
grep -q 'azerothlab_rocket_rescue_template_backup' "$repo_root/database/87-restore-rocket-rescue-vehicle-smartai.sql"
grep -q 'event_type.*= 73' "$repo_root/database/87-restore-rocket-rescue-vehicle-smartai.sql"
grep -q 'action_param1.*= 40511' "$repo_root/database/87-restore-rocket-rescue-vehicle-smartai.sql"
grep -q 'VehicleId.*= 752' "$repo_root/database/87-restore-rocket-rescue-vehicle-smartai.sql"
grep -q 'azerothlab_rocket_rescue_wdb_backup' "$repo_root/database/87-restore-rocket-rescue-vehicle-smartai.sql"
grep -q 'Displayid1.*= 31757' "$repo_root/database/87-restore-rocket-rescue-vehicle-smartai.sql"
grep -q "75560, 'spell_rocket_rescue_guided_payload'" "$repo_root/database/87-restore-rocket-rescue-vehicle-smartai.sql"
grep -q "73257, 'spell_rocket_rescue_guided_payload'" "$repo_root/database/87-restore-rocket-rescue-vehicle-smartai.sql"
grep -q 'database/87-restore-rocket-rescue-vehicle-smartai.sql' "$repo_root/scripts/apply-required-updates.sh"
grep -q 'database/87-restore-rocket-rescue-vehicle-smartai.sql' "$repo_root/scripts/prepare-runtime.sh"
grep -q 'azerothlab_olrun_phase_backup' "$repo_root/database/88-fix-olrun-deaths-challenge-phase.sql"
grep -q 'guid.*= 260740' "$repo_root/database/88-fix-olrun-deaths-challenge-phase.sql"
grep -q 'id.*= 29047' "$repo_root/database/88-fix-olrun-deaths-challenge-phase.sql"
grep -q 'phaseMask.*= 65535' "$repo_root/database/88-fix-olrun-deaths-challenge-phase.sql"
grep -q 'phaseMask.*= 1' "$repo_root/database/88-fix-olrun-deaths-challenge-phase.sql"
grep -q 'quest.*= 12733' "$repo_root/database/88-fix-olrun-deaths-challenge-phase.sql"
grep -q 'database/88-fix-olrun-deaths-challenge-phase.sql' "$repo_root/scripts/apply-required-updates.sh"
grep -q 'database/88-fix-olrun-deaths-challenge-phase.sql' "$repo_root/scripts/prepare-runtime.sh"
grep -q 'azerothlab_lightspoint_defender_smartai_backup' "$repo_root/database/89-fix-lights-point-defender-evade.sql"
grep -q 'entryorguid.*= 28834' "$repo_root/database/89-fix-lights-point-defender-evade.sql"
grep -q 'id.*IN (4, 5, 6, 7)' "$repo_root/database/89-fix-lights-point-defender-evade.sql"
grep -q 'action_type.*= 21' "$repo_root/database/89-fix-lights-point-defender-evade.sql"
grep -q 'action_param1.*= 52566' "$repo_root/database/89-fix-lights-point-defender-evade.sql"
grep -q 'action_param1.*= 28849' "$repo_root/database/89-fix-lights-point-defender-evade.sql"
grep -q 'database/89-fix-lights-point-defender-evade.sql' "$repo_root/scripts/apply-required-updates.sh"
grep -q 'database/89-fix-lights-point-defender-evade.sql' "$repo_root/scripts/prepare-runtime.sh"
grep -q 'azerothlab_orbaz_smartai_backup' "$repo_root/database/90-fix-orbaz-acherus-gate-recovery.sql"
grep -q 'entryorguid.*= 28914' "$repo_root/database/90-fix-orbaz-acherus-gate-recovery.sql"
grep -q '62, 609' "$repo_root/database/90-fix-orbaz-acherus-gate-recovery.sql"
grep -q 'database/90-fix-orbaz-acherus-gate-recovery.sql' "$repo_root/scripts/apply-required-updates.sh"
grep -q 'database/90-fix-orbaz-acherus-gate-recovery.sql' "$repo_root/scripts/prepare-runtime.sh"
grep -q 'azerothlab_ebon_hold_spell_area_backup' "$repo_root/database/91-fix-ebon-hold-battle-phase.sql"
grep -q 'spell.*= 53642' "$repo_root/database/91-fix-ebon-hold-battle-phase.sql"
grep -q '58361, 4281, 13166, 13166' "$repo_root/database/91-fix-ebon-hold-battle-phase.sql"
grep -q '58354, 4281, 12801, 13188' "$repo_root/database/91-fix-ebon-hold-battle-phase.sql"
grep -q '58354, 4281, 12801, 13189' "$repo_root/database/91-fix-ebon-hold-battle-phase.sql"
grep -q '2098253' "$repo_root/database/91-fix-ebon-hold-battle-phase.sql"
grep -q 'database/91-fix-ebon-hold-battle-phase.sql' "$repo_root/scripts/apply-required-updates.sh"
grep -q 'database/91-fix-ebon-hold-battle-phase.sql' "$repo_root/scripts/prepare-runtime.sh"
grep -q 'unlocktransmogs' "$repo_root/patches/0033-add-account-transmog-unlock-command.patch"
grep -q 'SEC_GAMEMASTER' "$repo_root/patches/0033-add-account-transmog-unlock-command.patch"
grep -q 'IsUnlockableTransmogAppearance' "$repo_root/patches/0033-add-account-transmog-unlock-command.patch"
grep -q 'BatchSize = 500' "$repo_root/patches/0033-add-account-transmog-unlock-command.patch"
grep -q 'AddTransmog(appearanceId, 0, false, false)' "$repo_root/patches/0033-add-account-transmog-unlock-command.patch"
grep -q 'azerothlab_account_transmogs_before_unlock' "$repo_root/database/92-add-account-transmog-unlock-audit.sql"
grep -q 'azerothlab_account_transmog_unlock_log' "$repo_root/database/92-add-account-transmog-unlock-audit.sql"
grep -q 'database/92-add-account-transmog-unlock-audit.sql' "$repo_root/scripts/apply-required-updates.sh"
grep -q 'database/92-add-account-transmog-unlock-audit.sql' "$repo_root/scripts/prepare-runtime.sh"
grep -q 'reward >= quest->m_rewChoiceItemsCount' "$repo_root/patches/0034-validate-selected-quest-rewards.patch"
grep -q 'CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, itemId' "$repo_root/patches/0034-validate-selected-quest-rewards.patch"
grep -q '29931.*Phantasmal Headdress' "$repo_root/database/93-restore-legacy-quest-reward-items.sql"
grep -q '29945.*Magistrate' "$repo_root/database/93-restore-legacy-quest-reward-items.sql"
grep -q 'INSERT INTO `item_sparse`' "$repo_root/database/93-restore-legacy-quest-reward-items.sql"
grep -q 'database/93-restore-legacy-quest-reward-items.sql' "$repo_root/scripts/apply-required-updates.sh"
grep -q 'database/93-restore-legacy-quest-reward-items.sql' "$repo_root/scripts/prepare-runtime.sh"
grep -q 'WowTime::EncodeLocal(ServerTime)' "$repo_root/patches/0023-use-local-realm-clock.patch"
grep -q 'ServerTimeTZ = \"\$server_timezone\"' "$repo_root/scripts/prepare-runtime.sh"
grep -q 'Quests.LowLevelHideDiff = -1' "$repo_root/scripts/prepare-runtime.sh"
grep -q 'LEGION_TIMEZONE:-America/Los_Angeles' "$repo_root/compose.yaml"
grep -q 'LEGION_TIMEZONE=America/Los_Angeles' "$repo_root/.env.example"
grep -q 'LEGION_RATE_PRESET=balanced' "$repo_root/.env.example"
grep -q 'LEGION_RATE_REPUTATION=2' "$repo_root/.env.example"
grep -q 'LEGION_RATE_PROFESSION=2' "$repo_root/.env.example"
grep -q 'LEGION_RATE_XP=1.25' "$repo_root/.env.example"
grep -q 'Rate.XP.Quest = \$LEGION_RATE_XP' "$repo_root/scripts/prepare-runtime.sh"
grep -q 'Rate.Reputation.Gain = \$LEGION_RATE_REPUTATION' "$repo_root/scripts/prepare-runtime.sh"
grep -q 'SkillGain.Crafting = \$LEGION_RATE_PROFESSION' "$repo_root/scripts/prepare-runtime.sh"
grep -q 'tzdata' "$repo_root/docker/runtime/Dockerfile"
bash -n "$repo_root/scripts/unlock-allied-races.sh"
grep -q 'raceID IN (27, 28, 29, 30)' "$repo_root/scripts/unlock-allied-races.sh"
grep -q '12242, 12243, 12244, 12245' "$repo_root/scripts/unlock-allied-races.sh"
grep -q 'account_achievement' "$repo_root/scripts/unlock-allied-races.sh"
grep -q 'battlenet_index' "$repo_root/scripts/unlock-allied-races.sh"

echo "fresh patch verification passed"
